### 圖片轉成hsv 滑鼠點圖輸出hsv值

https://blog.csdn.net/spw_1201/article/details/78310349

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img_path="/dataDisk/myfloder/jupyter/server/img/20190722141803"
image=cv2.imread(img_path)
HSV=cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
def getpos(event,x,y,flags,param):
    if event==cv2.EVENT_LBUTTONDOWN:
        print(HSV[y,x])
#th2=cv2.adaptiveThreshold(imagegray,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,11,2)
cv2.imshow("imageHSV",HSV)
#cv2.imshow('image',image)
cv2.setMouseCallback("imageHSV",getpos)
cv2.waitKey(0)
# #print (image(10,10,10))


# plt.figure(3,figsize=(8,8))
# plt.axis('off')
# plt.imshow(HSV)
# plt.show()

[  8  97 197]
[  4  77 211]
[  5  68 220]
